In [1]:
from polytrope import *

In [336]:
import numpy as np

def random_walk(n,x0=0,y0=0,z0=0,step='delta'):
    
    # recipe for choosing a random direction on a unit sphere
    
    rand = lambda : np.random.uniform(-1,1,n)
    x1,x2 = rand(),rand()
    
    a = x1**2 + x2**2
    
    idx = np.argwhere( a <= 1 )
    x1,x2,a = x1[idx].flatten(),x2[idx].flatten(),a[idx].flatten()
    
    b = np.sqrt(1-a)
    
    dx =  2*x1*b
    dy =  2*x2*b
    dz =  1-2*a
    
    if step == 'exp':
        s = np.random.exponential(scale=1.0,size=len(dx))
        dx*=s
        dy*=s
        dz*=s
        
    if step == 'tri':
        s = np.random.triangular(0,1.5,1.5,size=len(dx))
        dx*=s
        dy*=s
        dz*=s
    
    x = x0 + np.cumsum(dx)
    y = y0 + np.cumsum(dy)
    z = z0 + np.cumsum(dz)
    
    return x[-1],y[-1],z[-1], np.sqrt( x**2 + y**2 + z**2 )

def random_steps_until(dist,step='delta'):
    
    n = 0
    x0,y0,z0=0,0,0
    k = dist
    
    while True:
    
        x0,y0,z0,r = random_walk(int(k*k),x0,y0,z0,step )
        
        cond = np.argwhere(r >= dist).flatten()
        
        if len(cond) > 0:
            return n + cond[0] + 1
    
        n += len(r)
        k = max(10,dist-r[-1])


In [312]:
vals = np.array([random_steps_until(50,step='delta') for i in range(100000) ])

In [318]:
vals_exp = np.array([random_steps_until(50,step='exp') for i in range(100000) ])

In [339]:
vals_tri = np.array([random_steps_until(50,step='tri') for i in range(100000) ])

In [315]:
np.mean(vals)

2526.3703500000001

In [316]:
np.std(vals)

1601.1428415512705

In [317]:
np.median(vals)

2101.0

In [40]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


`%matplotlib` prevents importing * from pylab and numpy


In [323]:
grid(True)
xlabel('iterations')
ylabel('normalized occurrences')

hist(vals,bins=100,normed=True)



(array([  8.85947047e-06,   8.03971487e-05,   2.07077393e-04,
          3.08553971e-04,   3.65682281e-04,   3.89765784e-04,
          3.85488798e-04,   3.62729124e-04,   3.37780041e-04,
          3.04786151e-04,   2.75254582e-04,   2.43737271e-04,
          2.17871690e-04,   1.86710794e-04,   1.64663951e-04,
          1.49490835e-04,   1.30957230e-04,   1.15274949e-04,
          1.03920570e-04,   8.95112016e-05,   8.09572301e-05,
          6.87372709e-05,   6.15071283e-05,   5.34623218e-05,
          4.77596741e-05,   4.03767821e-05,   3.86965377e-05,
          3.32484725e-05,   2.70875764e-05,   2.45417515e-05,
          2.24541752e-05,   1.76680244e-05,   1.74643585e-05,
          1.57331976e-05,   1.25763747e-05,   1.30346232e-05,
          1.11507128e-05,   9.67413442e-06,   8.04480652e-06,
          7.68839104e-06,   6.87372709e-06,   5.90631365e-06,
          5.44806517e-06,   3.46232179e-06,   4.22606925e-06,
          3.20773931e-06,   2.80040733e-06,   2.34215886e-06,
        

In [341]:
grid(True)
xlabel('iterations')
ylabel('normalized occurrences')

hist(vals,bins=100,histtype='step',normed=True,linewidth='2')
hist(vals_exp,bins=100,histtype='step',normed=True,linewidth='2')
hist(vals_tri,bins=100,histtype='step',normed=True,linewidth='2')

(array([  7.30098917e-06,   7.13612812e-05,   2.04839849e-04,
          3.28780028e-04,   4.04439472e-04,   4.38118229e-04,
          4.34703250e-04,   4.17098446e-04,   3.91309468e-04,
          3.46325954e-04,   3.24128592e-04,   2.85621762e-04,
          2.54886952e-04,   2.26683938e-04,   2.01424870e-04,
          1.84114461e-04,   1.56735751e-04,   1.42133773e-04,
          1.25235516e-04,   1.09514837e-04,   9.90343853e-05,
          8.61398964e-05,   7.95454545e-05,   6.46490815e-05,
          5.51695714e-05,   5.44630240e-05,   4.55134244e-05,
          4.05675930e-05,   3.60927932e-05,   3.17946302e-05,
          3.09703250e-05,   2.46113990e-05,   1.94889308e-05,
          1.83702308e-05,   1.72515309e-05,   1.72515309e-05,
          1.37187942e-05,   1.10692416e-05,   1.08926048e-05,
          8.47856806e-06,   9.00847857e-06,   6.06453132e-06,
          5.88789449e-06,   5.00471032e-06,   5.24022610e-06,
          4.59255770e-06,   3.76825247e-06,   3.94488931e-06,
        

In [325]:
np.mean(vals_exp)

1286.1559600000001

In [281]:
x2,y2,z2,r2 = random_walk(2500,x,y,z)

In [263]:
plot(r2)

In [282]:
plot(np.append(r,r2))

In [270]:
np.append( np.arange(5), np.arange(5) )

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [217]:
r

array([  1.        ,   1.9640993 ,   2.32734777, ...,  31.56517228,
        32.51711058,  32.40616846])

In [225]:
a = 1 + np.arange(10)

In [224]:
np.cumsum(np.arange(10))

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [226]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [227]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [297]:
np.random.exponential(size=len(r))

array([ 0.75948463,  0.17151996,  0.03098001, ...,  1.33090742,
        1.35831705,  0.98850738])

In [298]:
rand = lambda : np.random.uniform(-1,1,n)
x1,x2 = rand(),rand()
    
a = x1**2 + x2**2
    
idx = np.argwhere( a <= 1 )
x1,x2,a = x1[idx],x2[idx],a[idx]

In [299]:
x1

array([[-0.21670655],
       [-0.66863481],
       [ 0.45965086],
       ..., 
       [ 0.41517618],
       [-0.6170463 ],
       [ 0.51495991]])

In [329]:
np.log(2)

0.69314718055994529

In [330]:
 h = plt.hist(np.random.triangular(0, 1.5,1.5, 100000), bins=200, normed=True)

In [331]:
tri=np.random.triangular(0, 1.5,1.5, 100000)

In [333]:
np.mean(tri)

1.0004141202306827